version: '3.2'
services:
 waifu-editor-web:
   build: .
   volumes:
     - ./app:/var/www/html
   restart: on-failure
   ports:
     - "11011:80"
   networks:
     - waifu-editor-network

networks:
  waifu-editor-network:
    driver: overlay
    attachable: true
